version: "3.8"

services:
  client:
    build: ../client
    ports:
      - "5173:5173"
    volumes:
      - ../client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000/api

  server:
    build: ../server
    ports:
      - "5000:5000"
    volumes:
      - ../server:/app
      - /app/node_modules
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/smart-transit
      - ML_SERVICE_URL=http://ml-service:8000
    depends_on:
      - mongo
      - ml-service

  ml-service:
    build: ../ml-service
    ports:
      - "8000:8000"
    volumes:
      - ../ml-service:/app
    environment:
      - PORT=8000

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
